apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-go-latest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-go-latest
    app.kubernetes.io/part-of: simple-go
  name: simple-go-latest
  namespace: rh-ee-chernand
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: simple-go-latest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: simple-go-latest
    spec:
      containers:
      - image: quay.io/christianh814/simple-go:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: "1"
            memory: 512Mi
status: {}
