apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-go-latest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-go-latest
    app.kubernetes.io/part-of: simple-go
  name: simple-go-latest
  namespace: rh-ee-chernand
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: simple-go-latest
    weight: 100
status: {}
